# Generated by Django 4.2.4 on 2023-09-21 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(verbose_name='Finished at')),
                ('finished_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_finished_by', to=settings.AUTH_USER_MODEL, verbose_name='Finished by')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_started_by', to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
            ],
        ),
    ]
