# Generated by Django 4.2.4 on 2023-09-22 10:33

from django.db import migrations, models
import queue_manager.session.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Code'),
        ),
    ]
