# Generated by Django 4.2.4 on 2023-09-22 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0004_alter_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_finished_by', to=settings.AUTH_USER_MODEL, verbose_name='Finished by'),
        ),
    ]
