# Generated by Django 4.2.4 on 2024-01-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_session_finished_at_alter_session_finished_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
