# Generated by Django 4.2.4 on 2024-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_remove_session_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at'], name='started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['finished_at'], name='finished_at_idx'),
        ),
    ]
