# Generated by Django 4.2.4 on 2024-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_session_started_at_idx_session_finished_at_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='finished_at_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['finished_at', '-started_at'], name='finishedat_startedat_idx'),
        ),
    ]
