# Generated by Django 4.2.4 on 2024-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_remove_session_finishedat_startedat_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='started_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='finished_at_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at', 'id'], name='started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['finished_at', 'id'], name='finished_at_idx'),
        ),
    ]
