# Generated by Django 4.2.4 on 2024-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_remove_session_started_at_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='started_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='finished_at_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at'], include=('id',), name='started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('finished_at__isnull', True)), fields=['finished_at'], include=('id',), name='finished_at_idx'),
        ),
    ]
