# Generated by Django 4.2.4 on 2023-09-11 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='letter_code',
            field=models.CharField(max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only English letters are allowed.')], verbose_name='Letter code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Name'),
        ),
    ]
