# Generated by Django 4.2.4 on 2023-09-11 10:07

import django.core.validators
from django.db import migrations
import queue_manager.task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_letter_code_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=queue_manager.task.models.CapitalizedCharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='letter_code',
            field=queue_manager.task.models.CapitalizedCharField(max_length=1, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only English letters are allowed.')], verbose_name='Letter code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=queue_manager.task.models.CapitalizedCharField(max_length=75, unique=True, verbose_name='Name'),
        ),
    ]
