# Generated by Django 4.2.4 on 2023-11-01 13:52
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0003_alter_task_description_alter_task_letter_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_servicing', models.BooleanField(default=False)),
                ('priority_for_operator', models.SmallIntegerField(null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.operator')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='can_be_served_by',
            field=models.ManyToManyField(through='task.Service', to='user.operator'),
        ),
    ]
