# Generated by Django 4.2.4 on 2023-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0005_alter_task_can_be_served_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='can_be_served_by',
            field=models.ManyToManyField(blank=True, through='task.Service', to='user.operator'),
        ),
    ]
