# Generated by Django 4.2.4 on 2023-12-05 19:50

import django.core.validators
from django.db import migrations
import queue_manager.task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='letter_code',
            field=queue_manager.task.models.CapitalizedCharField(max_length=1, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only English letters are allowed.')], verbose_name='Letter code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=queue_manager.task.models.CapitalizedCharField(max_length=75, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('letter_code', 'deleted_at')},
        ),
    ]
