# Generated by Django 4.2.4 on 2023-12-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_letter_code_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
