# Generated by Django 4.2.4 on 2023-12-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('letter_code',), name='unique_if_not_deleted'),
        ),
    ]
