# Generated by Django 4.2.4 on 2024-01-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_unique_if_not_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
