# Generated by Django 4.2.4 on 2024-01-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_servicing',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='priority_for_operator',
            new_name='priority'),
        migrations.AlterField(
            model_name='service',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
