# Generated by Django 4.2.4 on 2023-12-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_operator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('pretend_operator', 'Can serve tickets pretending to be any of the operators')]},
        ),
    ]
