# Generated by Django 4.2.4 on 2024-01-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_operator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('pretend_operator', 'Can serve tickets pretending to be any of the operators')]},
        ),
    ]
