# Generated by Django 4.2.4 on 2023-11-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0003_alter_status_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
