# Generated by Django 4.2.4 on 2023-10-30 10:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
    ]
