# Generated by Django 4.2.4 on 2023-10-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0004_auto_20231030_1138'),
    ]

    operations = [
    ]
