# Generated by Django 4.2.4 on 2023-10-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0009_auto_20231031_0952'),
    ]

    operations = [
    ]
