# Generated by Django 4.2.4 on 2023-10-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0010_auto_20231031_1318'),
    ]

    operations = [
    ]
